### ISSUE TITLE
Safari (and Sublime) freakout about </script> in a comment

### ISSUE THREAD

**Issue by soffes** [usecanvas/sharejs-wrapper#5]
https://github.com/usecanvas/sharejs-wrapper/blob/master/dist/index.js#L2726

It would be great if we could remove this :)

**Comment by jclem** [comment]
Ugh, this is rough. It's actually part of ShareJS, which I just pull in. Uglifying would solve this, but that'll mess up our error reporting unless we send or bundle source maps. I'll try and update the Makefile to just pull this string out :( :( :(

**Comment by soffes** [comment]
What if we just strip comments in make?

**Comment by jclem** [comment]
@soffes That's what uglifying would do. I'm sure there's also something I can use to just strip comments without uglifying, or I'll just build it myself.

**Comment by soffes** [comment]
Sounds good to me!

**Comment by jclem** [comment]
Closed by e93561cd018c531fb2ae8eac03bb3d63e3828d8d
